/*
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ru.iaie.reflexold.ReflexOldRuntimeModule;
import ru.iaie.reflexold.ReflexOldStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ReflexOldIdeSetup extends ReflexOldStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ReflexOldRuntimeModule(), new ReflexOldIdeModule()));
	}
	
}
