/*
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractReflexOldValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ru.iaie.reflexold.reflexOld.ReflexOldPackage.eINSTANCE);
		return result;
	}
}
