/*
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import ru.iaie.reflexold.parser.antlr.internal.InternalReflexOldParser;
import ru.iaie.reflexold.services.ReflexOldGrammarAccess;

public class ReflexOldParser extends AbstractAntlrParser {

	@Inject
	private ReflexOldGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReflexOldParser createParser(XtextTokenStream stream) {
		return new InternalReflexOldParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ReflexOldGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReflexOldGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
