/*
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ReflexOldAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ru/iaie/reflexold/parser/antlr/internal/InternalReflexOld.tokens");
	}
}
