/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.AssignmentExpression#getAssignVar <em>Assign Var</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.AssignmentExpression#getAssignOp <em>Assign Op</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.AssignmentExpression#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getAssignmentExpression()
 * @model
 * @generated
 */
public interface AssignmentExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Assign Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assign Var</em>' reference.
   * @see #setAssignVar(IdReference)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getAssignmentExpression_AssignVar()
   * @model
   * @generated
   */
  IdReference getAssignVar();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.AssignmentExpression#getAssignVar <em>Assign Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assign Var</em>' reference.
   * @see #getAssignVar()
   * @generated
   */
  void setAssignVar(IdReference value);

  /**
   * Returns the value of the '<em><b>Assign Op</b></em>' attribute.
   * The literals are from the enumeration {@link ru.iaie.reflexold.reflexOld.AssignOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assign Op</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.AssignOperator
   * @see #setAssignOp(AssignOperator)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getAssignmentExpression_AssignOp()
   * @model
   * @generated
   */
  AssignOperator getAssignOp();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.AssignmentExpression#getAssignOp <em>Assign Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assign Op</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.AssignOperator
   * @see #getAssignOp()
   * @generated
   */
  void setAssignOp(AssignOperator value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(LogicalOrExpression)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getAssignmentExpression_Expr()
   * @model containment="true"
   * @generated
   */
  LogicalOrExpression getExpr();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.AssignmentExpression#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(LogicalOrExpression value);

} // AssignmentExpression
