/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bit Or Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getBitOrExpression()
 * @model
 * @generated
 */
public interface BitOrExpression extends LogicalAndExpression
{
} // BitOrExpression
