/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bit Xor Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getBitXorExpression()
 * @model
 * @generated
 */
public interface BitXorExpression extends BitOrExpression
{
} // BitXorExpression
