/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check State Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.CheckStateExpression#isLogicalNot <em>Logical Not</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.CheckStateExpression#getProcess <em>Process</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.CheckStateExpression#getQualfier <em>Qualfier</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getCheckStateExpression()
 * @model
 * @generated
 */
public interface CheckStateExpression extends CompareExpression
{
  /**
   * Returns the value of the '<em><b>Logical Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logical Not</em>' attribute.
   * @see #setLogicalNot(boolean)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getCheckStateExpression_LogicalNot()
   * @model
   * @generated
   */
  boolean isLogicalNot();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.CheckStateExpression#isLogicalNot <em>Logical Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logical Not</em>' attribute.
   * @see #isLogicalNot()
   * @generated
   */
  void setLogicalNot(boolean value);

  /**
   * Returns the value of the '<em><b>Process</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process</em>' reference.
   * @see #setProcess(ru.iaie.reflexold.reflexOld.Process)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getCheckStateExpression_Process()
   * @model
   * @generated
   */
  ru.iaie.reflexold.reflexOld.Process getProcess();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.CheckStateExpression#getProcess <em>Process</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process</em>' reference.
   * @see #getProcess()
   * @generated
   */
  void setProcess(ru.iaie.reflexold.reflexOld.Process value);

  /**
   * Returns the value of the '<em><b>Qualfier</b></em>' attribute.
   * The literals are from the enumeration {@link ru.iaie.reflexold.reflexOld.StateQualifier}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualfier</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.StateQualifier
   * @see #setQualfier(StateQualifier)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getCheckStateExpression_Qualfier()
   * @model
   * @generated
   */
  StateQualifier getQualfier();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.CheckStateExpression#getQualfier <em>Qualfier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qualfier</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.StateQualifier
   * @see #getQualfier()
   * @generated
   */
  void setQualfier(StateQualifier value);

} // CheckStateExpression
