/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.Enum#getEnumMembers <em>Enum Members</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getEnum()
 * @model
 * @generated
 */
public interface Enum extends EObject
{
  /**
   * Returns the value of the '<em><b>Enum Members</b></em>' containment reference list.
   * The list contents are of type {@link ru.iaie.reflexold.reflexOld.EnumMember}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Members</em>' containment reference list.
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getEnum_EnumMembers()
   * @model containment="true"
   * @generated
   */
  EList<EnumMember> getEnumMembers();

} // Enum
