/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Infix Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.InfixOp#getOp <em>Op</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.InfixOp#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getInfixOp()
 * @model
 * @generated
 */
public interface InfixOp extends UnaryExpression
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link ru.iaie.reflexold.reflexOld.InfixPostfixOp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.InfixPostfixOp
   * @see #setOp(InfixPostfixOp)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getInfixOp_Op()
   * @model
   * @generated
   */
  InfixPostfixOp getOp();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.InfixOp#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.InfixPostfixOp
   * @see #getOp()
   * @generated
   */
  void setOp(InfixPostfixOp value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(IdReference)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getInfixOp_Ref()
   * @model
   * @generated
   */
  IdReference getRef();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.InfixOp#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(IdReference value);

} // InfixOp
