/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical And Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getLogicalAndExpression()
 * @model
 * @generated
 */
public interface LogicalAndExpression extends LogicalOrExpression
{
} // LogicalAndExpression
