/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.PortMapping#getPort <em>Port</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.PortMapping#getBits <em>Bits</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPortMapping()
 * @model
 * @generated
 */
public interface PortMapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' reference.
   * @see #setPort(Port)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPortMapping_Port()
   * @model
   * @generated
   */
  Port getPort();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.PortMapping#getPort <em>Port</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' reference.
   * @see #getPort()
   * @generated
   */
  void setPort(Port value);

  /**
   * Returns the value of the '<em><b>Bits</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bits</em>' attribute.
   * @see #setBits(String)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPortMapping_Bits()
   * @model
   * @generated
   */
  String getBits();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.PortMapping#getBits <em>Bits</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bits</em>' attribute.
   * @see #getBits()
   * @generated
   */
  void setBits(String value);

} // PortMapping
