/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getReference <em>Reference</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getInteger <em>Integer</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getFloating <em>Floating</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getBool <em>Bool</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getNestedExpr <em>Nested Expr</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPrimaryExpression()
 * @model
 * @generated
 */
public interface PrimaryExpression extends UnaryExpression
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' reference.
   * @see #setReference(IdReference)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPrimaryExpression_Reference()
   * @model
   * @generated
   */
  IdReference getReference();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getReference <em>Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' reference.
   * @see #getReference()
   * @generated
   */
  void setReference(IdReference value);

  /**
   * Returns the value of the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Integer</em>' attribute.
   * @see #setInteger(String)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPrimaryExpression_Integer()
   * @model
   * @generated
   */
  String getInteger();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getInteger <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Integer</em>' attribute.
   * @see #getInteger()
   * @generated
   */
  void setInteger(String value);

  /**
   * Returns the value of the '<em><b>Floating</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Floating</em>' attribute.
   * @see #setFloating(String)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPrimaryExpression_Floating()
   * @model
   * @generated
   */
  String getFloating();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getFloating <em>Floating</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Floating</em>' attribute.
   * @see #getFloating()
   * @generated
   */
  void setFloating(String value);

  /**
   * Returns the value of the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' attribute.
   * @see #setBool(Boolean)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPrimaryExpression_Bool()
   * @model
   * @generated
   */
  Boolean getBool();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getBool <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' attribute.
   * @see #getBool()
   * @generated
   */
  void setBool(Boolean value);

  /**
   * Returns the value of the '<em><b>Nested Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested Expr</em>' containment reference.
   * @see #setNestedExpr(Expression)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getPrimaryExpression_NestedExpr()
   * @model containment="true"
   * @generated
   */
  Expression getNestedExpr();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.PrimaryExpression#getNestedExpr <em>Nested Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nested Expr</em>' containment reference.
   * @see #getNestedExpr()
   * @generated
   */
  void setNestedExpr(Expression value);

} // PrimaryExpression
