/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.ProgramVariable#isLocal <em>Local</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.ProgramVariable#isShared <em>Shared</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.ProgramVariable#getProcesses <em>Processes</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.ProgramVariable#getType <em>Type</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.ProgramVariable#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getProgramVariable()
 * @model
 * @generated
 */
public interface ProgramVariable extends ProcessVariable, IdReference
{
  /**
   * Returns the value of the '<em><b>Local</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local</em>' attribute.
   * @see #setLocal(boolean)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getProgramVariable_Local()
   * @model
   * @generated
   */
  boolean isLocal();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.ProgramVariable#isLocal <em>Local</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Local</em>' attribute.
   * @see #isLocal()
   * @generated
   */
  void setLocal(boolean value);

  /**
   * Returns the value of the '<em><b>Shared</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shared</em>' attribute.
   * @see #setShared(boolean)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getProgramVariable_Shared()
   * @model
   * @generated
   */
  boolean isShared();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.ProgramVariable#isShared <em>Shared</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shared</em>' attribute.
   * @see #isShared()
   * @generated
   */
  void setShared(boolean value);

  /**
   * Returns the value of the '<em><b>Processes</b></em>' reference list.
   * The list contents are of type {@link ru.iaie.reflexold.reflexOld.Process}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processes</em>' reference list.
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getProgramVariable_Processes()
   * @model
   * @generated
   */
  EList<ru.iaie.reflexold.reflexOld.Process> getProcesses();

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link ru.iaie.reflexold.reflexOld.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.Type
   * @see #setType(Type)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getProgramVariable_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.ProgramVariable#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.Type
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getProgramVariable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.ProgramVariable#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // ProgramVariable
