/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Time Amount Or Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.TimeAmountOrRef#getTime <em>Time</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.TimeAmountOrRef#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getTimeAmountOrRef()
 * @model
 * @generated
 */
public interface TimeAmountOrRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(String)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getTimeAmountOrRef_Time()
   * @model
   * @generated
   */
  String getTime();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.TimeAmountOrRef#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(String value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(IdReference)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getTimeAmountOrRef_Ref()
   * @model
   * @generated
   */
  IdReference getRef();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.TimeAmountOrRef#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(IdReference value);

} // TimeAmountOrRef
