/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getType()
 * @model
 * @generated
 */
public enum Type implements Enumerator
{
  /**
   * The '<em><b>VOID EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VOID_EN_VALUE
   * @generated
   * @ordered
   */
  VOID_EN(0, "VOID_EN", "VOID"),

  /**
   * The '<em><b>VOID RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VOID_RU_VALUE
   * @generated
   * @ordered
   */
  VOID_RU(1, "VOID_RU", "\u041f\u0423\u0421\u0422\u041e"),

  /**
   * The '<em><b>FLOAT EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FLOAT_EN_VALUE
   * @generated
   * @ordered
   */
  FLOAT_EN(2, "FLOAT_EN", "FLOAT"),

  /**
   * The '<em><b>FLOAT RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FLOAT_RU_VALUE
   * @generated
   * @ordered
   */
  FLOAT_RU(3, "FLOAT_RU", "\u041f\u041b\u0410\u0412"),

  /**
   * The '<em><b>DOUBLE EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DOUBLE_EN_VALUE
   * @generated
   * @ordered
   */
  DOUBLE_EN(4, "DOUBLE_EN", "DOUBLE"),

  /**
   * The '<em><b>DOUBLE RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DOUBLE_RU_VALUE
   * @generated
   * @ordered
   */
  DOUBLE_RU(5, "DOUBLE_RU", "\u0414\u041f\u041b\u0410\u0412"),

  /**
   * The '<em><b>SHORT EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHORT_EN_VALUE
   * @generated
   * @ordered
   */
  SHORT_EN(6, "SHORT_EN", "SHORT"),

  /**
   * The '<em><b>SHORT RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHORT_RU_VALUE
   * @generated
   * @ordered
   */
  SHORT_RU(7, "SHORT_RU", "\u041a\u0426\u0415\u041b"),

  /**
   * The '<em><b>USHORT EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USHORT_EN_VALUE
   * @generated
   * @ordered
   */
  USHORT_EN(8, "USHORT_EN", "UNSIGNED SHORT"),

  /**
   * The '<em><b>USHORT RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USHORT_RU_VALUE
   * @generated
   * @ordered
   */
  USHORT_RU(9, "USHORT_RU", "\u0411\u0415\u0417\u0417\u041d\u0410\u041a\u041e\u0412\u041e\u0415 \u041a\u0426\u0415\u041b"),

  /**
   * The '<em><b>INT EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INT_EN_VALUE
   * @generated
   * @ordered
   */
  INT_EN(10, "INT_EN", "INT"),

  /**
   * The '<em><b>INT RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INT_RU_VALUE
   * @generated
   * @ordered
   */
  INT_RU(11, "INT_RU", "\u0426\u0415\u041b"),

  /**
   * The '<em><b>UINT EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UINT_EN_VALUE
   * @generated
   * @ordered
   */
  UINT_EN(12, "UINT_EN", "UNSIGNED INT"),

  /**
   * The '<em><b>UINT RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UINT_RU_VALUE
   * @generated
   * @ordered
   */
  UINT_RU(13, "UINT_RU", "\u0411\u0415\u0417\u0417\u041d\u0410\u041a\u041e\u0412\u041e\u0415 \u0426\u0415\u041b"),

  /**
   * The '<em><b>LONG EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LONG_EN_VALUE
   * @generated
   * @ordered
   */
  LONG_EN(14, "LONG_EN", "LONG"),

  /**
   * The '<em><b>LONG RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LONG_RU_VALUE
   * @generated
   * @ordered
   */
  LONG_RU(15, "LONG_RU", "\u0414\u0426\u0415\u041b"),

  /**
   * The '<em><b>ULONG EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ULONG_EN_VALUE
   * @generated
   * @ordered
   */
  ULONG_EN(16, "ULONG_EN", "UNSIGNED LONG"),

  /**
   * The '<em><b>ULONG RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ULONG_RU_VALUE
   * @generated
   * @ordered
   */
  ULONG_RU(17, "ULONG_RU", "\u0411\u0415\u0417\u0417\u041d\u0410\u041a\u041e\u0412\u041e\u0415 \u0414\u0426\u0415\u041b"),

  /**
   * The '<em><b>BOOL EN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOOL_EN_VALUE
   * @generated
   * @ordered
   */
  BOOL_EN(18, "BOOL_EN", "LOG"),

  /**
   * The '<em><b>BOOL RU</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOOL_RU_VALUE
   * @generated
   * @ordered
   */
  BOOL_RU(19, "BOOL_RU", "\u041b\u041e\u0413");

  /**
   * The '<em><b>VOID EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VOID_EN
   * @model literal="VOID"
   * @generated
   * @ordered
   */
  public static final int VOID_EN_VALUE = 0;

  /**
   * The '<em><b>VOID RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VOID_RU
   * @model literal="\u041f\u0423\u0421\u0422\u041e"
   * @generated
   * @ordered
   */
  public static final int VOID_RU_VALUE = 1;

  /**
   * The '<em><b>FLOAT EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FLOAT_EN
   * @model literal="FLOAT"
   * @generated
   * @ordered
   */
  public static final int FLOAT_EN_VALUE = 2;

  /**
   * The '<em><b>FLOAT RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FLOAT_RU
   * @model literal="\u041f\u041b\u0410\u0412"
   * @generated
   * @ordered
   */
  public static final int FLOAT_RU_VALUE = 3;

  /**
   * The '<em><b>DOUBLE EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DOUBLE_EN
   * @model literal="DOUBLE"
   * @generated
   * @ordered
   */
  public static final int DOUBLE_EN_VALUE = 4;

  /**
   * The '<em><b>DOUBLE RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DOUBLE_RU
   * @model literal="\u0414\u041f\u041b\u0410\u0412"
   * @generated
   * @ordered
   */
  public static final int DOUBLE_RU_VALUE = 5;

  /**
   * The '<em><b>SHORT EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHORT_EN
   * @model literal="SHORT"
   * @generated
   * @ordered
   */
  public static final int SHORT_EN_VALUE = 6;

  /**
   * The '<em><b>SHORT RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHORT_RU
   * @model literal="\u041a\u0426\u0415\u041b"
   * @generated
   * @ordered
   */
  public static final int SHORT_RU_VALUE = 7;

  /**
   * The '<em><b>USHORT EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USHORT_EN
   * @model literal="UNSIGNED SHORT"
   * @generated
   * @ordered
   */
  public static final int USHORT_EN_VALUE = 8;

  /**
   * The '<em><b>USHORT RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USHORT_RU
   * @model literal="\u0411\u0415\u0417\u0417\u041d\u0410\u041a\u041e\u0412\u041e\u0415 \u041a\u0426\u0415\u041b"
   * @generated
   * @ordered
   */
  public static final int USHORT_RU_VALUE = 9;

  /**
   * The '<em><b>INT EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INT_EN
   * @model literal="INT"
   * @generated
   * @ordered
   */
  public static final int INT_EN_VALUE = 10;

  /**
   * The '<em><b>INT RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INT_RU
   * @model literal="\u0426\u0415\u041b"
   * @generated
   * @ordered
   */
  public static final int INT_RU_VALUE = 11;

  /**
   * The '<em><b>UINT EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UINT_EN
   * @model literal="UNSIGNED INT"
   * @generated
   * @ordered
   */
  public static final int UINT_EN_VALUE = 12;

  /**
   * The '<em><b>UINT RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UINT_RU
   * @model literal="\u0411\u0415\u0417\u0417\u041d\u0410\u041a\u041e\u0412\u041e\u0415 \u0426\u0415\u041b"
   * @generated
   * @ordered
   */
  public static final int UINT_RU_VALUE = 13;

  /**
   * The '<em><b>LONG EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LONG_EN
   * @model literal="LONG"
   * @generated
   * @ordered
   */
  public static final int LONG_EN_VALUE = 14;

  /**
   * The '<em><b>LONG RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LONG_RU
   * @model literal="\u0414\u0426\u0415\u041b"
   * @generated
   * @ordered
   */
  public static final int LONG_RU_VALUE = 15;

  /**
   * The '<em><b>ULONG EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ULONG_EN
   * @model literal="UNSIGNED LONG"
   * @generated
   * @ordered
   */
  public static final int ULONG_EN_VALUE = 16;

  /**
   * The '<em><b>ULONG RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ULONG_RU
   * @model literal="\u0411\u0415\u0417\u0417\u041d\u0410\u041a\u041e\u0412\u041e\u0415 \u0414\u0426\u0415\u041b"
   * @generated
   * @ordered
   */
  public static final int ULONG_RU_VALUE = 17;

  /**
   * The '<em><b>BOOL EN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOOL_EN
   * @model literal="LOG"
   * @generated
   * @ordered
   */
  public static final int BOOL_EN_VALUE = 18;

  /**
   * The '<em><b>BOOL RU</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOOL_RU
   * @model literal="\u041b\u041e\u0413"
   * @generated
   * @ordered
   */
  public static final int BOOL_RU_VALUE = 19;

  /**
   * An array of all the '<em><b>Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Type[] VALUES_ARRAY =
    new Type[]
    {
      VOID_EN,
      VOID_RU,
      FLOAT_EN,
      FLOAT_RU,
      DOUBLE_EN,
      DOUBLE_RU,
      SHORT_EN,
      SHORT_RU,
      USHORT_EN,
      USHORT_RU,
      INT_EN,
      INT_RU,
      UINT_EN,
      UINT_RU,
      LONG_EN,
      LONG_RU,
      ULONG_EN,
      ULONG_RU,
      BOOL_EN,
      BOOL_RU,
    };

  /**
   * A public read-only list of all the '<em><b>Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Type> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Type result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Type result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type get(int value)
  {
    switch (value)
    {
      case VOID_EN_VALUE: return VOID_EN;
      case VOID_RU_VALUE: return VOID_RU;
      case FLOAT_EN_VALUE: return FLOAT_EN;
      case FLOAT_RU_VALUE: return FLOAT_RU;
      case DOUBLE_EN_VALUE: return DOUBLE_EN;
      case DOUBLE_RU_VALUE: return DOUBLE_RU;
      case SHORT_EN_VALUE: return SHORT_EN;
      case SHORT_RU_VALUE: return SHORT_RU;
      case USHORT_EN_VALUE: return USHORT_EN;
      case USHORT_RU_VALUE: return USHORT_RU;
      case INT_EN_VALUE: return INT_EN;
      case INT_RU_VALUE: return INT_RU;
      case UINT_EN_VALUE: return UINT_EN;
      case UINT_RU_VALUE: return UINT_RU;
      case LONG_EN_VALUE: return LONG_EN;
      case LONG_RU_VALUE: return LONG_RU;
      case ULONG_EN_VALUE: return ULONG_EN;
      case ULONG_RU_VALUE: return ULONG_RU;
      case BOOL_EN_VALUE: return BOOL_EN;
      case BOOL_RU_VALUE: return BOOL_RU;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Type(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Type
