/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.iaie.reflexold.reflexOld.UnaryExpression#isReferenceOp <em>Reference Op</em>}</li>
 *   <li>{@link ru.iaie.reflexold.reflexOld.UnaryExpression#getUnaryOp <em>Unary Op</em>}</li>
 * </ul>
 *
 * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getUnaryExpression()
 * @model
 * @generated
 */
public interface UnaryExpression extends CastExpression
{
  /**
   * Returns the value of the '<em><b>Reference Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Op</em>' attribute.
   * @see #setReferenceOp(boolean)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getUnaryExpression_ReferenceOp()
   * @model
   * @generated
   */
  boolean isReferenceOp();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.UnaryExpression#isReferenceOp <em>Reference Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference Op</em>' attribute.
   * @see #isReferenceOp()
   * @generated
   */
  void setReferenceOp(boolean value);

  /**
   * Returns the value of the '<em><b>Unary Op</b></em>' attribute.
   * The literals are from the enumeration {@link ru.iaie.reflexold.reflexOld.UnaryOp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary Op</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.UnaryOp
   * @see #setUnaryOp(UnaryOp)
   * @see ru.iaie.reflexold.reflexOld.ReflexOldPackage#getUnaryExpression_UnaryOp()
   * @model
   * @generated
   */
  UnaryOp getUnaryOp();

  /**
   * Sets the value of the '{@link ru.iaie.reflexold.reflexOld.UnaryExpression#getUnaryOp <em>Unary Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary Op</em>' attribute.
   * @see ru.iaie.reflexold.reflexOld.UnaryOp
   * @see #getUnaryOp()
   * @generated
   */
  void setUnaryOp(UnaryOp value);

} // UnaryExpression
