/*
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ReflexOldUiModule extends AbstractReflexOldUiModule {

	public ReflexOldUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
