/*
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ru.iaie.reflexold.ui.internal.ReflexoldActivator;

public class ReflexOldUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ReflexoldActivator.getInstance().getInjector("ru.iaie.reflexold.ReflexOld");
	}

}
