/*
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReflexOldScopeProvider extends DelegatingScopeProvider {
}
