/**
 * generated by Xtext 2.25.0
 */
package ru.iaie.reflexold.reflexOld.impl;

import org.eclipse.emf.ecore.EClass;

import ru.iaie.reflexold.reflexOld.ReflexOldPackage;
import ru.iaie.reflexold.reflexOld.ResetStat;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reset Stat</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ResetStatImpl extends StatementImpl implements ResetStat
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ResetStatImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReflexOldPackage.Literals.RESET_STAT;
  }

} //ResetStatImpl
